/**
 * Sequelize Tenant Seeder: Initial Seed Data for Tenant Databases
 * Location: server/src/tenant-configuration/seeders/tenantSeeders.js
 *
 * Deliberately light-touch: one or two representative rows per reference/master
 * table so a developer has something real to look at, not bulk-generated fake
 * data. Tables that are pure event/transaction logs generated by actual user
 * actions (journal_entries, eod_records, superadmin_audit_logs, repayment
 * schedules) are left empty on purpose — pre-seeding those risks producing
 * numbers that look real but were never actually earned by any action, which is
 * worse than an empty table for development.
 */

export async function up(queryInterface, Sequelize) {
  // 0. Tenant Staff Directory
  await queryInterface.bulkInsert('users', [
    { company_id: 1, name: 'John Admin', email: 'admin@alpha.com', phone: '9840000001', password: 'admin123', role: 'COMPANY_ADMIN', status: 'ACTIVE' },
    { company_id: 1, name: 'Sarah Collector', email: 'sarah@alpha.com', phone: '9840000002', password: 'sarah123', role: 'COLLECTOR', status: 'ACTIVE' },
    { company_id: 1, name: 'Mike Manager', email: 'mike@alpha.com', phone: '9840000003', password: 'mike123', role: 'MANAGER', status: 'ACTIVE' }
  ]);

  // 0b. Branches
  await queryInterface.bulkInsert('branches', [
    { company_id: 1, name: 'Karur Branch', code: 'KRM', address: 'Main Road, Karur', city: 'Karur', state: 'Tamil Nadu', pincode: '639001', phone: '9840000010', is_active: true },
    { company_id: 1, name: 'Chennai Branch', code: 'CHN', address: 'T Nagar, Chennai', city: 'Chennai', state: 'Tamil Nadu', pincode: '600017', phone: '9840000011', is_active: true }
  ]);

  // 0c. Staff <-> Branch assignment (Sarah collects for the Karur branch)
  await queryInterface.bulkInsert('user_branches', [
    { company_id: 1, user_id: 2, branch_id: 1 }
  ]);

  // 1. Chart of Accounts Defaults
  await queryInterface.bulkInsert('chart_of_accounts', [
    { account_code: '1001', account_name: 'Cash in Hand', name_key: 'coa.cash_in_hand', account_type: 'ASSET', category: 'CURRENT_ASSETS', balance: 150000.00, is_active: true },
    { account_code: '1002', account_name: 'HDFC Bank Account', name_key: 'coa.bank_account', account_type: 'ASSET', category: 'BANK_ACCOUNTS', balance: 500000.00, is_active: true },
    { account_code: '1100', account_name: 'Loan Receivables Portfolio', name_key: 'coa.loan_receivables', account_type: 'ASSET', category: 'LOAN_PORTFOLIO', balance: 0.00, is_active: true },
    { account_code: '2001', account_name: 'Promoter Share Capital', name_key: 'coa.share_capital', account_type: 'EQUITY', category: 'CAPITAL', balance: 650000.00, is_active: true },
    { account_code: '4001', account_name: 'Loan Interest Income', name_key: 'coa.interest_income', account_type: 'REVENUE', category: 'OPERATING_INCOME', balance: 0.00, is_active: true },
    { account_code: '4002', account_name: 'Loan Penalty / Overdue Fee Income', name_key: 'coa.penalty_income', account_type: 'REVENUE', category: 'OTHER_INCOME', balance: 0.00, is_active: true },
    { account_code: '5001', account_name: 'Bad Debt Provision Expense', name_key: 'coa.bad_debt_provision', account_type: 'EXPENSE', category: 'PROVISIONS', balance: 0.00, is_active: true },
    { account_code: '5002', account_name: 'Branch Operating Expenses', name_key: 'coa.operating_expenses', account_type: 'EXPENSE', category: 'ADMINISTRATIVE', balance: 0.00, is_active: true }
  ]);

  // 2. Default Loan Schemes
  await queryInterface.bulkInsert('loan_schemes', [
    {
      name: 'Standard Daily Collection Scheme',
      unit_base: 1000.00,
      rate_per_unit: 10.0000,
      formula_type: 'STANDARD',
      repayment_method: 'EMI',
      interest_calculation: 'CONSTANT_FLAT',
      interest_basis: 'MONTHLY',
      repayment_frequency: 'DAILY',
      min_amount: 5000.00,
      max_amount: 100000.00,
      min_tenure_months: 1,
      max_tenure_months: 6,
      is_active: true
    },
    {
      name: 'Flexible Reducing Interest Scheme',
      unit_base: 1000.00,
      rate_per_unit: 18.0000,
      formula_type: 'STANDARD',
      repayment_method: 'EMI',
      interest_calculation: 'FLEXIBLE_REDUCING',
      interest_basis: 'MONTHLY',
      repayment_frequency: 'MONTHLY',
      min_amount: 25000.00,
      max_amount: 500000.00,
      min_tenure_months: 3,
      max_tenure_months: 36,
      is_active: true
    }
  ]);

  // 3. Initial Sample Borrowers — column names match the real borrowers table now
  // (aadhaar_number/pan_number, split address fields), not the old short names.
  await queryInterface.bulkInsert('borrowers', [
    {
      borrower_code: 'BR-0001',
      full_name: 'Rajesh Kumar',
      phone: '9876543210',
      email: 'rajesh@example.com',
      aadhaar_number: '458912348971',
      pan_number: 'ABCDE1234F',
      address_line1: 'Main St 123',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600001',
      guarantor_name: 'Mahesh Kumar',
      branch: 'Karur Branch',
      status: 'ACTIVE',
      kyc_status: 'VERIFIED'
    },
    {
      borrower_code: 'BR-0002',
      full_name: 'Priya Sharma',
      phone: '9812345678',
      email: 'priya@example.com',
      aadhaar_number: '891234567890',
      pan_number: 'XYZPD9876K',
      address_line1: 'Market Road 45',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600002',
      guarantor_name: 'Sunil Sharma',
      branch: 'Karur Branch',
      status: 'ACTIVE',
      kyc_status: 'VERIFIED'
    }
  ]);

  // 4. One sample loan per borrower, one per scheme type, so the Loans/Collections
  // screens have something real instead of looking broken/empty on first run.
  await queryInterface.bulkInsert('loans', [
    {
      loan_account_no: 'LN-2026-0001',
      borrower_id: 1,
      borrower_name: 'Rajesh Kumar',
      phone: '9876543210',
      scheme_id: 1,
      branch: 'Karur Branch',
      collector: 'Sarah Collector',
      principal_amount: 50000.00,
      total_payable: 55000.00,
      collected_amount: 0.00,
      pending_amount: 55000.00,
      installment_amount: 500.00,
      monthly_interest_rate: 10.0000,
      tenure_days: 110,
      repayment_method: 'EMI',
      interest_calculation: 'CONSTANT_FLAT',
      repayment_frequency: 'DAILY',
      status: 'ACTIVE',
      loan_date: '2026-06-01',
      next_due: '2026-06-02'
    }
  ]);

  // 5. Investors — top-level capital providers, master/reference data.
  await queryInterface.bulkInsert('investors', [
    {
      investor_code: 'INV-0001',
      name: 'Karthik Investments Pvt Ltd',
      phone: '9840012345',
      email: 'karthik@example.com',
      city: 'Chennai',
      state: 'Tamil Nadu',
      kyc_status: 'VERIFIED',
      bank_name: 'HDFC Bank',
      account_holder_name: 'Karthik Investments Pvt Ltd',
      account_no: '50100123456789',
      ifsc_no: 'HDFC0001234',
      capital_amount: 650000.00,
      join_date: '2026-01-15',
      yield_rate: 12.000,
      status: 'ACTIVE'
    }
  ]);

  // 6. One sample Fixed Deposit and Recurring Deposit, each tied to a real borrower.
  await queryInterface.bulkInsert('fixed_deposits', [
    {
      fd_account_no: 'FD-2026-0001',
      borrower_id: 2,
      customer_name: 'Priya Sharma',
      branch: 'Karur Branch',
      principal_amount: 100000.00,
      tenure_months: 12,
      interest_rate: 7.50,
      scheme: 'CUMULATIVE',
      payment_mode: 'BANK_TRANSFER',
      booking_date: '2026-05-01',
      maturity_date: '2027-05-01',
      status: 'ACTIVE'
    }
  ]);

  // Only RD row in a fresh table, so its auto-increment id is deterministically 1
  // — the installments below reference it directly rather than round-tripping an
  // insertId through bulkInsert (which doesn't surface one).
  await queryInterface.bulkInsert('recurring_deposits', [
    {
      rd_account_no: 'RD-2026-0001',
      borrower_id: 1,
      customer_name: 'Rajesh Kumar',
      branch: 'Karur Branch',
      monthly_installment: 2000.00,
      tenure_months: 6,
      interest_rate: 6.50,
      payment_mode: 'CASH',
      booking_date: '2026-04-01',
      maturity_date: '2026-10-01',
      collected_amount: 0.00,
      status: 'ACTIVE'
    }
  ]);

  // RD installment schedule — deterministic (month N due date = booking date + N
  // months), not fabricated payment history; every installment starts PENDING.
  await queryInterface.bulkInsert('recurring_deposit_installments',
    Array.from({ length: 6 }, (_, i) => ({
      rd_id: 1,
      month_no: i + 1,
      due_date: new Date(2026, 4 + i, 1).toISOString().slice(0, 10),
      amount: 2000.00,
      status: 'PENDING'
    }))
  );

  // 7. Expense allocation module — a couple of standing categories branches draw
  // vouchers against.
  await queryInterface.bulkInsert('expense_categories', [
    { name: 'Branch Operations', status: 'ACTIVE', balance: 25000.00, allocated_total: 25000.00 },
    { name: 'Staff Welfare', status: 'ACTIVE', balance: 10000.00, allocated_total: 10000.00 }
  ]);

  // 8. Standard Indian currency denominations for the EOD cash-count form — a
  // real config table, not fabricated transaction data, so seeding it is safe.
  await queryInterface.bulkInsert('eod_denomination_settings',
    [500, 200, 100, 50, 20, 10, 5, 2, 1].map(value => ({ value, enabled: true }))
  );
}

// Used for real tenant provisioning (server/src/core/tenantProvisioner.js) instead
// of `up` above — `up` is ALPHA-specific local dev/demo content (named people,
// a fake login for admin@alpha.com, sample loans). Running that for every
// real SuperAdmin-provisioned tenant would be wrong in two ways: it dumps
// someone else's demo data into a brand-new company's database, AND it creates
// an admin@alpha.com login inside every tenant's database, which is a genuine
// cross-tenant credential collision — that email+password would then work
// against every newly provisioned tenant, not just the ALPHA sandbox.
// This is only the structural defaults every real tenant actually needs
// (a starting chart of accounts, EOD cash-count denominations); the tenant's
// own admin user is inserted separately by tenantProvisioner.js from the real
// admin_email/admin_password the SuperAdmin actually typed in.
export async function seedDefaults(queryInterface) {
  await queryInterface.bulkInsert('chart_of_accounts', [
    { account_code: '1001', account_name: 'Cash in Hand', name_key: 'coa.cash_in_hand', account_type: 'ASSET', category: 'CURRENT_ASSETS', balance: 0.00, is_active: true },
    { account_code: '1002', account_name: 'Bank Account', name_key: 'coa.bank_account', account_type: 'ASSET', category: 'BANK_ACCOUNTS', balance: 0.00, is_active: true },
    { account_code: '1100', account_name: 'Loan Receivables Portfolio', name_key: 'coa.loan_receivables', account_type: 'ASSET', category: 'LOAN_PORTFOLIO', balance: 0.00, is_active: true },
    { account_code: '2001', account_name: 'Promoter Share Capital', name_key: 'coa.share_capital', account_type: 'EQUITY', category: 'CAPITAL', balance: 0.00, is_active: true },
    { account_code: '4001', account_name: 'Loan Interest Income', name_key: 'coa.interest_income', account_type: 'REVENUE', category: 'OPERATING_INCOME', balance: 0.00, is_active: true },
    { account_code: '4002', account_name: 'Loan Penalty / Overdue Fee Income', name_key: 'coa.penalty_income', account_type: 'REVENUE', category: 'OTHER_INCOME', balance: 0.00, is_active: true },
    { account_code: '5001', account_name: 'Bad Debt Provision Expense', name_key: 'coa.bad_debt_provision', account_type: 'EXPENSE', category: 'PROVISIONS', balance: 0.00, is_active: true },
    { account_code: '5002', account_name: 'Branch Operating Expenses', name_key: 'coa.operating_expenses', account_type: 'EXPENSE', category: 'ADMINISTRATIVE', balance: 0.00, is_active: true }
  ]);

  await queryInterface.bulkInsert('eod_denomination_settings',
    [500, 200, 100, 50, 20, 10, 5, 2, 1].map(value => ({ value, enabled: true }))
  );
}

export async function down(queryInterface) {
  await queryInterface.bulkDelete('eod_denomination_settings', null, {});
  await queryInterface.bulkDelete('expense_categories', null, {});
  await queryInterface.bulkDelete('recurring_deposit_installments', null, {});
  await queryInterface.bulkDelete('recurring_deposits', null, {});
  await queryInterface.bulkDelete('fixed_deposits', null, {});
  await queryInterface.bulkDelete('investors', null, {});
  await queryInterface.bulkDelete('loans', null, {});
  await queryInterface.bulkDelete('borrowers', null, {});
  await queryInterface.bulkDelete('loan_schemes', null, {});
  await queryInterface.bulkDelete('chart_of_accounts', null, {});
  await queryInterface.bulkDelete('user_branches', null, {});
  await queryInterface.bulkDelete('branches', null, {});
  await queryInterface.bulkDelete('users', null, {});
}
